services:
app:
  build:
    context: .
    dockerfile: Dockerfile
  container_name: app
  ports:
    - "32784:3000"
  volumes:
    - .:/app
    - /app/node_modulesfind .git/refs
  command: ["npm", "start"]
