name: Auto Deploy DockerHub

on:
  push:
    branches:
      - main  # main 브랜치에 push될 때마다 실행

jobs:
  test-docker:
    runs-on: ubuntu-latest

    steps:
      # 리포지토리 체크아웃
      - name: Check out the repository
        uses: actions/checkout@v3

      # Docker 로그인
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # 로그인 상태 확인
      - name: Verify Docker Login
        run: docker info
        
      # Docker 이미지 빌드
      - name: Build the Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}:latest .

      # Docker Hub에 이미지 푸시
      - name: Push the Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}:latest
