name: Test Docker Hub Connection

on:
  push:
    branches:
      - main  # main 브랜치에 push될 때마다 실행

jobs:
  test-docker:
    runs-on: ubuntu-latest

    steps:
      # 리포지토리 체크아웃
      - name: Check out the repository
        uses: actions/checkout@v3

      # Docker 로그인
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # 로그인 상태 확인
      - name: Verify Docker Login
        run: docker info
